<?php


namespace App\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AfdelingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('naam', TextType::class)
            ->add('locatie', ChoiceType::class, [
                'choices'=>[
                    'Delft'=>'Delft',
                    'Den Haag'=>'Den Haag',
                    'Naaldwijk'=>'Naaldwijk',
                    'Leidschendam'=>'Leidschendam',
                ]
            ])
            ;
    }
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => 'App\Entity\Afdeling'
        ]);
    }
}